---
title: "Codebook"
author: "Joe Rubash"
date: "September 11, 2016"
output: html_document
---

Codebook for Getting and Cleaning Data week 4 final assignment

variable names (other than subject and activity) have 4 parts; for example "tBodyAcc-mean()-X" can be broken in to "t", "BodyAcc", "mean()" and "X". Each part describes details of the measurement. Listed below are all measurement options by part and their definitions:

Part 1.
"t" = time domain signal
"f" = frequency domain signals

Part 2.
"BodyAcc" = body linear acceleration
"GravityAcc" = gravity linear acceleration
"BodyAccJerk" = jerking motion linear acceleration
"BodyGyro" = body angluar velocity
"BodyGyroJerk" = jeking motion angular velocity 
"BodyAccMag" = magnitude of body linear acceleration
"GravityAccMag" = magnitude of gravity linear acceleration
"BodyAccJerkMag" = magnitude of jerking motion linear acceleration
"BodyGyroMag" = magnitude of body angular velocity
"BodyGyroJerkMag" = magnitude of jerking motion angular velocity

Part 3.
"mean()" = mean of specific measurement
"std()" = standard deviation of specific measurement
"meanFreq" = weighted average of the frequency components to obtain a mean frequency

Part 4.
"X" = measurement taken along X axis
"Y" = measurement taken along Y axis
"Z" = measurement taken along Z axis


"tt_comb" tidy data 
This data set is the combination of test and train data sets from Human Activity Recognition Using Smartphones Data Set with subject and activity labels selecting only mean and std (standard deviation) data.

List of variables in "tt_comb" data set:
"subject" = the subject number being observed (ie the person being tested during the specific observation) 1 through 30 subects
"activity" = the activity being performed during observation. Activities inculded: walking walking_upstairs walking_downstairs sitting standing laying  

The remaining variables are the mean, standard deviation (std) and mean frequency (meanFreq) of specific measurements for each axis x, y and z. Features (variables) are normalized and bounded within [-1,1].Please refer to the assciated README.RMD for more information about these varialbes.
"tBodyAcc-mean()-X"   
"tBodyAcc-mean()-Y"  
"tBodyAcc-mean()-Z"      
"tBodyAcc-std()-X"               
"tBodyAcc-std()-Y"    
"tBodyAcc-std()-Z"            
"tGravityAcc-mean()-X"           
"tGravityAcc-mean()-Y"    
"tGravityAcc-mean()-Z"         
"tGravityAcc-std()-X"            
"tGravityAcc-std()-Y"     
"tGravityAcc-std()-Z"          
"tBodyAccJerk-mean()-X"          
"tBodyAccJerk-mean()-Y"   
"tBodyAccJerk-mean()-Z"        
"tBodyAccJerk-std()-X"           
"tBodyAccJerk-std()-Y"    
"tBodyAccJerk-std()-Z"        
"tBodyGyro-mean()-X"             
"tBodyGyro-mean()-Y"      
"tBodyGyro-mean()-Z"          
"tBodyGyro-std()-X"              
"tBodyGyro-std()-Y"      
"tBodyGyro-std()-Z"           
"tBodyGyroJerk-mean()-X"         
"tBodyGyroJerk-mean()-Y"     
"tBodyGyroJerk-mean()-Z"         
"tBodyGyroJerk-std()-X"          
"tBodyGyroJerk-std()-Y"    
"tBodyGyroJerk-std()-Z"         
"tBodyAccMag-mean()"             
"tBodyAccMag-std()"        
"tGravityAccMag-mean()"        
"tGravityAccMag-std()"           
"tBodyAccJerkMag-mean()"   
"tBodyAccJerkMag-std()"         
"tBodyGyroMag-mean()"            
"tBodyGyroMag-std()"       
"tBodyGyroJerkMag-mean()"     
"tBodyGyroJerkMag-std()"         
"fBodyAcc-mean()-X"     
"fBodyAcc-mean()-Y"          
"fBodyAcc-mean()-Z"              
"fBodyAcc-std()-X"      
"fBodyAcc-std()-Y"             
"fBodyAcc-std()-Z"               
"fBodyAcc-meanFreq()-X"    
"fBodyAcc-meanFreq()-Y"        
"fBodyAcc-meanFreq()-Z"          
"fBodyAccJerk-mean()-X"    
"fBodyAccJerk-mean()-Y"         
"fBodyAccJerk-mean()-Z"          
"fBodyAccJerk-std()-X"      
"fBodyAccJerk-std()-Y"         
"fBodyAccJerk-std()-Z"           
"fBodyAccJerk-meanFreq()-X"  
"fBodyAccJerk-meanFreq()-Y"     
"fBodyAccJerk-meanFreq()-Z"      
"fBodyGyro-mean()-X"      
"fBodyGyro-mean()-Y"           
"fBodyGyro-mean()-Z"             
"fBodyGyro-std()-X"         
"fBodyGyro-std()-Y"             
"fBodyGyro-std()-Z"              
"fBodyGyro-meanFreq()-X"     
"fBodyGyro-meanFreq()-Y"        
"fBodyGyro-meanFreq()-Z"         
"fBodyAccMag-mean()"        
"fBodyAccMag-std()"            
"fBodyAccMag-meanFreq()"         
"fBodyBodyAccJerkMag-mean()"    
"fBodyBodyAccJerkMag-std()"     
"fBodyBodyAccJerkMag-meanFreq()" 
"fBodyBodyGyroMag-mean()"      
"fBodyBodyGyroMag-std()"      
"fBodyBodyGyroMag-meanFreq()"    
"fBodyBodyGyroJerkMag-mean()"  
"fBodyBodyGyroJerkMag-std()"   
"fBodyBodyGyroJerkMag-meanFreq()"


"tt_comb_sum" tidy data also known as "summary_activity_data.csv"
This data set is a summary of the "tt_comb" data set taking the average of each variable grouped by subject and by activity.

List of variables in "tt_comb" data set:
"subject" = the subject number being observed (ie the person being tested during the specific observation) 1 through 30 subects
"activity" = the activity being performed during observation. Activities inculded: walking walking_upstairs walking_downstairs sitting standing laying  

The remaining variables are the mean, standard deviation (std) and mean frequency (meanFreq) of specific measurements for each axis x, y and z. Features (variables) are normalized and bounded within [-1,1].Please refer to the assciated README.RMD for more information about these varialbes.
"tBodyAcc-mean()-X"   
"tBodyAcc-mean()-Y"  
"tBodyAcc-mean()-Z"      
"tBodyAcc-std()-X"               
"tBodyAcc-std()-Y"    
"tBodyAcc-std()-Z"            
"tGravityAcc-mean()-X"           
"tGravityAcc-mean()-Y"    
"tGravityAcc-mean()-Z"         
"tGravityAcc-std()-X"            
"tGravityAcc-std()-Y"     
"tGravityAcc-std()-Z"          
"tBodyAccJerk-mean()-X"          
"tBodyAccJerk-mean()-Y"   
"tBodyAccJerk-mean()-Z"        
"tBodyAccJerk-std()-X"           
"tBodyAccJerk-std()-Y"    
"tBodyAccJerk-std()-Z"        
"tBodyGyro-mean()-X"             
"tBodyGyro-mean()-Y"      
"tBodyGyro-mean()-Z"          
"tBodyGyro-std()-X"              
"tBodyGyro-std()-Y"      
"tBodyGyro-std()-Z"           
"tBodyGyroJerk-mean()-X"         
"tBodyGyroJerk-mean()-Y"     
"tBodyGyroJerk-mean()-Z"         
"tBodyGyroJerk-std()-X"          
"tBodyGyroJerk-std()-Y"    
"tBodyGyroJerk-std()-Z"         
"tBodyAccMag-mean()"             
"tBodyAccMag-std()"        
"tGravityAccMag-mean()"        
"tGravityAccMag-std()"           
"tBodyAccJerkMag-mean()"   
"tBodyAccJerkMag-std()"         
"tBodyGyroMag-mean()"            
"tBodyGyroMag-std()"       
"tBodyGyroJerkMag-mean()"     
"tBodyGyroJerkMag-std()"         
"fBodyAcc-mean()-X"     
"fBodyAcc-mean()-Y"          
"fBodyAcc-mean()-Z"              
"fBodyAcc-std()-X"      
"fBodyAcc-std()-Y"             
"fBodyAcc-std()-Z"               
"fBodyAcc-meanFreq()-X"    
"fBodyAcc-meanFreq()-Y"        
"fBodyAcc-meanFreq()-Z"          
"fBodyAccJerk-mean()-X"    
"fBodyAccJerk-mean()-Y"         
"fBodyAccJerk-mean()-Z"          
"fBodyAccJerk-std()-X"      
"fBodyAccJerk-std()-Y"         
"fBodyAccJerk-std()-Z"           
"fBodyAccJerk-meanFreq()-X"  
"fBodyAccJerk-meanFreq()-Y"     
"fBodyAccJerk-meanFreq()-Z"      
"fBodyGyro-mean()-X"      
"fBodyGyro-mean()-Y"           
"fBodyGyro-mean()-Z"             
"fBodyGyro-std()-X"         
"fBodyGyro-std()-Y"             
"fBodyGyro-std()-Z"              
"fBodyGyro-meanFreq()-X"     
"fBodyGyro-meanFreq()-Y"        
"fBodyGyro-meanFreq()-Z"         
"fBodyAccMag-mean()"        
"fBodyAccMag-std()"            
"fBodyAccMag-meanFreq()"         
"fBodyBodyAccJerkMag-mean()"    
"fBodyBodyAccJerkMag-std()"     
"fBodyBodyAccJerkMag-meanFreq()" 
"fBodyBodyGyroMag-mean()"      
"fBodyBodyGyroMag-std()"      
"fBodyBodyGyroMag-meanFreq()"    
"fBodyBodyGyroJerkMag-mean()"  
"fBodyBodyGyroJerkMag-std()"   
"fBodyBodyGyroJerkMag-meanFreq()"
